#  Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import pandas as pd

In [2]:
import numpy as np

In [3]:
# warning
import warnings
warnings.filterwarnings('ignore')

In [4]:
#load given dataset
data = pd.read_csv("data1.csv")

In [5]:
data.head()

S.NO  Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     0   65  Female              0.7               0.1                   187   
1     1   62    Male             10.9               5.5                   699   
2     2   62    Male              7.3               4.1                   490   
3     3   58    Male              1.0               0.4                   182   
4     4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [6]:
#shape
data.shape

(5830, 12)

In [7]:
#size
data.size

69960

In [8]:
#Checking datatype and information about dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5830 entries, 0 to 5829
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Unnamed: 0                  5830 non-null   int64  
 1   Age                         5830 non-null   int64  
 2   Gender                      5830 non-null   object 
 3   Total_Bilirubin             5830 non-null   float64
 4   Direct_Bilirubin            5830 non-null   float64
 5   Alkaline_Phosphotase        5830 non-null   int64  
 6   Alamine_Aminotransferase    5830 non-null   int64  
 7   Aspartate_Aminotransferase  5830 non-null   int64  
 8   Total_Protiens              5830 non-null   float64
 9   Albumin                     5830 non-null   float64
 10  Albumin_and_Globulin_Ratio  5790 non-null   float64
 11  Dataset                     5830 non-null   int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 546.7+ KB


In [9]:
#To describe the dataframe
data.describe()

Unnamed: 0          Age  Total_Bilirubin  Direct_Bilirubin  \
count  5830.000000  5830.000000      5830.000000       5830.000000   
mean   2914.500000    44.746141         3.298799          1.486106   
std    1683.120366    16.177330         6.204726          2.806329   
min       0.000000     4.000000         0.400000          0.100000   
25%    1457.250000    33.000000         0.800000          0.200000   
50%    2914.500000    45.000000         1.000000          0.300000   
75%    4371.750000    58.000000         2.600000          1.300000   
max    5829.000000    90.000000        75.000000         19.700000   

       Alkaline_Phosphotase  Alamine_Aminotransferase  \
count           5830.000000               5830.000000   
mean             290.576329                 80.713551   
std              242.750368                182.479318   
min               63.000000                 10.000000   
25%              175.000000                 23.000000   
50%              208.000000                 35.000000   
75%              298.000000                 61.000000   
max             2110.000000               2000.000000   

       Aspartate_Aminotransferase  Total_Protiens      Albumin  \
count                 5830.000000     5830.000000  5830.000000   
mean                   109.910806        6.483190     3.141852   
std                    288.695397        1.084613     0.794904   
min                     10.000000        2.700000     0.900000   
25%                     25.000000        5.800000     2.600000   
50%                     42.000000        6.600000     3.100000   
75%                     87.000000        7.200000     3.800000   
max                   4929.000000        9.600000     5.500000   

       Albumin_and_Globulin_Ratio      Dataset  
count                 5790.000000  5830.000000  
mean                     0.947064     1.286449  
std                      0.319344     0.452141  
min                      0.300000     1.000000  
25%                      0.700000     1.000000  
50%                      0.930000     1.000000  
75%                      1.100000     2.000000  
max                      2.800000     2.000000

In [10]:
#duplicate data
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
5825    False
5826    False
5827    False
5828    False
5829    False
Length: 5830, dtype: bool

In [11]:
# sum of duplicated 
data.duplicated().sum()

0

In [12]:
data.shape

(5830, 12)

In [13]:
# null values
data.isnull()

Unnamed: 0    Age  Gender  Total_Bilirubin  Direct_Bilirubin  \
0          False  False   False            False             False   
1          False  False   False            False             False   
2          False  False   False            False             False   
3          False  False   False            False             False   
4          False  False   False            False             False   
...          ...    ...     ...              ...               ...   
5825       False  False   False            False             False   
5826       False  False   False            False             False   
5827       False  False   False            False             False   
5828       False  False   False            False             False   
5829       False  False   False            False             False   

      Alkaline_Phosphotase  Alamine_Aminotransferase  \
0                    False                     False   
1                    False                     False   
2                    False                     False   
3                    False                     False   
4                    False                     False   
...                    ...                       ...   
5825                 False                     False   
5826                 False                     False   
5827                 False                     False   
5828                 False                     False   
5829                 False                     False   

      Aspartate_Aminotransferase  Total_Protiens  Albumin  \
0                          False           False    False   
1                          False           False    False   
2                          False           False    False   
3                          False           False    False   
4                          False           False    False   
...                          ...             ...      ...   
5825                       False           False    False   
5826                       False           False    False   
5827                       False           False    False   
5828                       False           False    False   
5829                       False           False    False   

      Albumin_and_Globulin_Ratio  Dataset  
0                          False    False  
1                          False    False  
2                          False    False  
3                          False    False  
4                          False    False  
...                          ...      ...  
5825                       False    False  
5826                       False    False  
5827                       False    False  
5828                       False    False  
5829                       False    False  

[5830 rows x 12 columns]

In [14]:
#sum of null values
data.isnull().sum()

Unnamed: 0                     0
Age                            0
Gender                         0
Total_Bilirubin                0
Direct_Bilirubin               0
Alkaline_Phosphotase           0
Alamine_Aminotransferase       0
Aspartate_Aminotransferase     0
Total_Protiens                 0
Albumin                        0
Albumin_and_Globulin_Ratio    40
Dataset                        0
dtype: int64

In [15]:
# shape before drop null values
data.shape

(5830, 12)

In [16]:
#drop null values
df=data.dropna()

In [17]:
#drop after drop null values
df.shape

(5790, 12)

In [18]:
df.isnull().sum()

Unnamed: 0                    0
Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [19]:
#changing feature name
df = df.rename({'Dataset': 'Result'}, axis=1) 

In [20]:
df.head(10)

Unnamed: 0  Age  Gender  Total_Bilirubin  Direct_Bilirubin  \
0           0   65  Female              0.7               0.1   
1           1   62    Male             10.9               5.5   
2           2   62    Male              7.3               4.1   
3           3   58    Male              1.0               0.4   
4           4   72    Male              3.9               2.0   
5           5   46    Male              1.8               0.7   
6           6   26  Female              0.9               0.2   
7           7   29  Female              0.9               0.3   
8           8   17    Male              0.9               0.3   
9           9   55    Male              0.7               0.2   

   Alkaline_Phosphotase  Alamine_Aminotransferase  Aspartate_Aminotransferase  \
0                   187                        16                          18   
1                   699                        64                         100   
2                   490                        60                          68   
3                   182                        14                          20   
4                   195                        27                          59   
5                   208                        19                          14   
6                   154                        16                          12   
7                   202                        14                          11   
8                   202                        22                          19   
9                   290                        53                          58   

   Total_Protiens  Albumin  Albumin_and_Globulin_Ratio  Result  
0             6.8      3.3                        0.90       1  
1             7.5      3.2                        0.74       1  
2             7.0      3.3                        0.89       1  
3             6.8      3.4                        1.00       1  
4             7.3      2.4                        0.40       1  
5             7.6      4.4                        1.30       1  
6             7.0      3.5                        1.00       1  
7             6.7      3.6                        1.10       1  
8             7.4      4.1                        1.20       2  
9             6.8      3.4                        1.00       1

In [21]:
df.columns

Index(['Unnamed: 0', 'Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Result'],
      dtype='object')

In [22]:
df.Result.unique()

array([1, 2], dtype=int64)

In [23]:
df.Age.unique()

array([65, 62, 58, 72, 46, 26, 29, 17, 55, 57, 64, 74, 61, 25, 38, 33, 40,
       51, 63, 34, 20, 84, 52, 30, 48, 47, 45, 42, 50, 85, 35, 21, 32, 31,
       54, 37, 66, 60, 19, 75, 68, 70, 49, 14, 13, 18, 39, 27, 36, 24, 28,
       53, 15, 56, 44, 41,  7, 22,  8,  6,  4, 43, 23, 12, 69, 16, 78, 11,
       73, 67, 10, 90], dtype=int64)

In [24]:
df['Total_Bilirubin'].unique()

array([ 0.7, 10.9,  7.3,  1. ,  3.9,  1.8,  0.9,  0.6,  2.7,  1.1,  1.6,
        2.2,  2.9,  6.8,  1.9,  4.1,  6.2,  4. ,  2.6,  1.3, 14.2,  1.4,
        2.4, 18.4,  3.1,  8.9,  0.8,  2.8,  2. ,  5.7,  8.6,  5.8,  5.2,
        3.8,  6.6,  0.5,  5.3,  3.2,  1.2, 12.7, 15.9, 18. , 23. , 22.7,
        1.7,  3. , 11.3,  4.7,  4.2,  3.5,  5.9,  8.7, 11. , 11.5,  4.5,
       75. , 22.8, 14.1, 14.8, 10.6,  8. ,  1.5,  2.1,  6.3,  2.3, 27.2,
        2.5,  3.6, 30.5, 16.4, 14.5, 18.5, 23.2,  3.7,  3.3,  7.1,  6.7,
       22.6,  7.5,  5. ,  4.9,  8.2,  0.4,  7.4, 23.3,  7.9,  3.4, 19.8,
       32.6, 17.7, 20. , 26.3,  4.4,  9.4, 30.8, 19.6, 15.8,  5.5, 20.2,
       27.7, 11.1, 10.2, 42.8, 15.2, 16.6, 17.3, 22.5, 16.7,  7.7, 15.6,
       12.1, 25. , 15. ])

In [25]:
df[ 'Direct_Bilirubin'].unique()

array([ 0.1,  5.5,  4.1,  0.4,  2. ,  0.7,  0.2,  0.3,  1.3,  0.8,  0.5,
        1. ,  3. ,  1.9,  1.2,  7.8,  0.6,  1.1,  3.2,  1.8,  8.8,  1.6,
        4.5,  2.8,  4. ,  2.7,  2.4,  1.5,  2.3,  3.6,  6.2,  7. ,  8.2,
       11.3, 10.2,  2.5,  1.4,  1.7,  5.6,  2.2,  2.1,  4.9,  5. ,  0.9,
       12.6,  7.6,  9. ,  4.6, 11.8, 14.2,  8.9,  6.4,  9.5,  3.3, 11.4,
        4.3,  3.7,  2.6,  3.9,  5.1, 12.8, 10.4, 17.1, 14.1,  8.5, 10. ,
       12.1,  2.9,  5.2, 18.3,  7.2, 11.7, 10.8,  6.1,  4.2, 19.7,  7.7,
        8.4,  6. , 13.7])

In [26]:
df['Alkaline_Phosphotase'].unique()

array([ 187,  699,  490,  182,  195,  208,  154,  202,  290,  210,  260,
        310,  214,  145,  183,  342,  165,  293,  610,  482,  542,  231,
        194,  289,  240,  128,  188,  190,  156,  410,  374,  263,  275,
        168,  160,  630,  415,  150,  230,  176,  206,  170,  161,  253,
        198,  272,  175,  367,  158,  259,  470,  215,  239,  186,  205,
        171,  162,  518, 1620,  146,  670,  915,   75,  148,  258,  237,
        269,  320,  298,  538,  238,  308,  204,  282,  265,  312,  243,
        224,  225,  486,  257,  179,  661, 1580, 1630,  280,  300,  178,
        177,  201,  802,  248, 1896,  512,  199, 1110,  380,  159,  332,
        189,  392,  286,  180,  218,  462,  196,  750, 1050,  599,  292,
        962,  950,  200, 1020,  562,  386,  250,  191,  614,  314,  209,
       1124,  664,  142,  169, 1420,  135,  163,  285,  350,  220,  219,
        401,  100,  116,  125,  147,  192,  400,  120,  173,  157, 2110,
        360,  316,  498,  480,  680,  152,  859,  9

In [27]:
df['Alamine_Aminotransferase'].unique()

array([  16,   64,   60,   14,   27,   19,   22,   53,   51,   31,   61,
         91,  168,   15,  232,   17,  116,   52,  875, 1680,   20,   13,
         45,   35,   59,  102,   18,   38,  123,   33,   42,   25,  407,
         48,   36, 1630,   39,   21,   80,   86,   26,   24,   37,   40,
         62,   55,  166,  189,   95,   12,  194,   58,   28,  119,  412,
        404,  220,  126,  190,   97,  308,   32,   29,   11,   63,  181,
         88,   74, 2000, 1350, 1250,  482,  322,  133,   46,   57,   50,
         34,   72,   84,   30,   70,  140,   99,   43,  378,  112,   71,
         23,   79,  114,  118,  107,  790,  950,   82,   41,   56,   85,
        149,  230,   69,   90,   89,  148,   65,  205,   96,  152,  390,
         10,  120,   78,  178,  179,   47,  160,   54,  198,   44,  349,
        110,  115,   94,  142,  137,  155,  157,  141,  284,  440,   93,
         76,   49,  425,  159,  622,  779,  132,  154,  196,   68,  509,
         67,  139,  382,   75,  321,  233,  173,  2

In [28]:
df['Alamine_Aminotransferase'].unique()

array([  16,   64,   60,   14,   27,   19,   22,   53,   51,   31,   61,
         91,  168,   15,  232,   17,  116,   52,  875, 1680,   20,   13,
         45,   35,   59,  102,   18,   38,  123,   33,   42,   25,  407,
         48,   36, 1630,   39,   21,   80,   86,   26,   24,   37,   40,
         62,   55,  166,  189,   95,   12,  194,   58,   28,  119,  412,
        404,  220,  126,  190,   97,  308,   32,   29,   11,   63,  181,
         88,   74, 2000, 1350, 1250,  482,  322,  133,   46,   57,   50,
         34,   72,   84,   30,   70,  140,   99,   43,  378,  112,   71,
         23,   79,  114,  118,  107,  790,  950,   82,   41,   56,   85,
        149,  230,   69,   90,   89,  148,   65,  205,   96,  152,  390,
         10,  120,   78,  178,  179,   47,  160,   54,  198,   44,  349,
        110,  115,   94,  142,  137,  155,  157,  141,  284,  440,   93,
         76,   49,  425,  159,  622,  779,  132,  154,  196,   68,  509,
         67,  139,  382,   75,  321,  233,  173,  2

In [29]:
df['Total_Protiens'].unique()

array([6.8, 7.5, 7. , 7.3, 7.6, 6.7, 7.4, 5.9, 8.1, 5.8, 5.5, 6.4, 4.3,
       6. , 5. , 7.2, 3.9, 5.2, 4.9, 5.6, 6.9, 6.2, 5.1, 6.1, 6.5, 5.7,
       6.6, 6.3, 8. , 4.4, 5.3, 4.6, 4.7, 5.4, 7.1, 4. , 3.7, 2.7, 3. ,
       3.8, 7.8, 4.5, 4.1, 4.8, 7.9, 8.5, 7.7, 8.2, 2.8, 9.5, 9.6, 8.3,
       8.6, 8.4, 8.9, 8.7, 3.6, 9.2])

In [30]:
df['Albumin'].unique()

array([3.3, 3.2, 3.4, 2.4, 4.4, 3.5, 3.6, 4.1, 2.7, 3. , 2.3, 3.1, 2.6,
       1.6, 3.9, 4. , 1.9, 1.5, 2.9, 2. , 2.2, 2.8, 1.8, 2.5, 2.1, 3.7,
       3.8, 4.3, 1.7, 4.2, 4.5, 0.9, 1.4, 4.7, 5.5, 4.9, 4.6, 5. , 4.8,
       1. ])

In [32]:
df['Albumin_and_Globulin_Ratio'].unique()

array([0.9 , 0.74, 0.89, 1.  , 0.4 , 1.3 , 1.1 , 1.2 , 0.8 , 0.6 , 0.87,
       0.7 , 0.92, 0.55, 0.5 , 1.85, 0.95, 1.4 , 1.18, 0.61, 1.34, 1.39,
       1.6 , 1.58, 1.25, 0.78, 0.76, 1.55, 0.71, 0.62, 0.67, 0.75, 1.16,
       1.5 , 1.66, 0.96, 1.38, 0.52, 0.47, 0.93, 0.48, 0.58, 0.69, 1.27,
       1.12, 1.06, 0.53, 1.03, 0.68, 1.9 , 1.7 , 1.8 , 0.3 , 0.97, 0.35,
       1.51, 0.64, 0.45, 1.36, 0.88, 1.09, 1.11, 1.72, 2.8 , 0.46, 0.39,
       1.02, 2.5 , 0.37])

In [34]:
df.corr()

Unnamed: 0       Age  Total_Bilirubin  \
Unnamed: 0                    1.000000 -0.005243         0.010129   
Age                          -0.005243  1.000000         0.011000   
Total_Bilirubin               0.010129  0.011000         1.000000   
Direct_Bilirubin              0.013613  0.006784         0.874481   
Alkaline_Phosphotase         -0.007964  0.078878         0.205739   
Alamine_Aminotransferase     -0.012584 -0.087799         0.213375   
Aspartate_Aminotransferase   -0.009487 -0.020499         0.237323   
Total_Protiens                0.019032 -0.186248        -0.007906   
Albumin                       0.006630 -0.264211        -0.222087   
Albumin_and_Globulin_Ratio   -0.002493 -0.216408        -0.206267   
Result                        0.001859 -0.133164        -0.220218   

                            Direct_Bilirubin  Alkaline_Phosphotase  \
Unnamed: 0                          0.013613             -0.007964   
Age                                 0.006784              0.078878   
Total_Bilirubin                     0.874481              0.205739   
Direct_Bilirubin                    1.000000              0.234008   
Alkaline_Phosphotase                0.234008              1.000000   
Alamine_Aminotransferase            0.233180              0.124777   
Aspartate_Aminotransferase          0.257022              0.166580   
Total_Protiens                      0.000033             -0.027062   
Albumin                            -0.228409             -0.163419   
Albumin_and_Globulin_Ratio         -0.200125             -0.234166   
Result                             -0.246273             -0.183363   

                            Alamine_Aminotransferase  \
Unnamed: 0                                 -0.012584   
Age                                        -0.087799   
Total_Bilirubin                             0.213375   
Direct_Bilirubin                            0.233180   
Alkaline_Phosphotase                        0.124777   
Alamine_Aminotransferase                    1.000000   
Aspartate_Aminotransferase                  0.791862   
Total_Protiens                             -0.042432   
Albumin                                    -0.028658   
Albumin_and_Globulin_Ratio                 -0.002375   
Result                                     -0.163117   

                            Aspartate_Aminotransferase  Total_Protiens  \
Unnamed: 0                                   -0.009487        0.019032   
Age                                          -0.020499       -0.186248   
Total_Bilirubin                               0.237323       -0.007906   
Direct_Bilirubin                              0.257022        0.000033   
Alkaline_Phosphotase                          0.166580       -0.027062   
Alamine_Aminotransferase                      0.791862       -0.042432   
Aspartate_Aminotransferase                    1.000000       -0.025751   
Total_Protiens                               -0.025751        1.000000   
Albumin                                      -0.084915        0.783112   
Albumin_and_Globulin_Ratio                   -0.070040        0.234887   
Result                                       -0.151834        0.033614   

                             Albumin  Albumin_and_Globulin_Ratio    Result  
Unnamed: 0                  0.006630                   -0.002493  0.001859  
Age                        -0.264211                   -0.216408 -0.133164  
Total_Bilirubin            -0.222087                   -0.206267 -0.220218  
Direct_Bilirubin           -0.228409                   -0.200125 -0.246273  
Alkaline_Phosphotase       -0.163419                   -0.234166 -0.183363  
Alamine_Aminotransferase   -0.028658                   -0.002375 -0.163117  
Aspartate_Aminotransferase -0.084915                   -0.070040 -0.151834  
Total_Protiens              0.783112                    0.234887  0.033614  
Albumin                     1.000000                    0.689632  0.159770  
Albumin_and_Globulin_Ratio

In [35]:
df.columns

Index(['Unnamed: 0', 'Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Result'],
      dtype='object')

In [36]:
pd.Categorical(df['Age']).describe()

counts     freqs
categories                  
4               20  0.003454
6               10  0.001727
7               20  0.003454
8               10  0.001727
10              10  0.001727
...            ...       ...
75             140  0.024180
78              10  0.001727
84              10  0.001727
85              10  0.001727
90              10  0.001727

[72 rows x 2 columns]

In [37]:
pd.Categorical(df['Gender']).describe()

counts     freqs
categories                  
Female        1400  0.241796
Male          4390  0.758204

In [38]:
pd.Categorical(df['Result']).describe()

counts     freqs
categories                  
1             4140  0.715026
2             1650  0.284974

In [39]:
df["Alkaline_Phosphotase"].min()

63

In [40]:
df["Alkaline_Phosphotase"].max()

2110

In [41]:
df["Alkaline_Phosphotase"].mean()

291.36614853195164

In [42]:
df["Age"].sort_values().unique()

array([ 4,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75,
       78, 84, 85, 90], dtype=int64)

In [43]:
df.columns

Index(['Unnamed: 0', 'Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Result'],
      dtype='object')

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
var_mod = {'Gender'}
le=LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [46]:
df.head()

Unnamed: 0  Age  Gender  Total_Bilirubin  Direct_Bilirubin  \
0           0   65       0              0.7               0.1   
1           1   62       1             10.9               5.5   
2           2   62       1              7.3               4.1   
3           3   58       1              1.0               0.4   
4           4   72       1              3.9               2.0   

   Alkaline_Phosphotase  Alamine_Aminotransferase  Aspartate_Aminotransferase  \
0                   187                        16                          18   
1                   699                        64                         100   
2                   490                        60                          68   
3                   182                        14                          20   
4                   195                        27                          59   

   Total_Protiens  Albumin  Albumin_and_Globulin_Ratio  Result  
0             6.8      3.3                        0.90       1  
1             7.5      3.2                        0.74       1  
2             7.0      3.3                        0.89       1  
3             6.8      3.4                        1.00       1  
4             7.3      2.4                        0.40       1